name: "GitHub Classroom Workflow"
on: 
- "pull_request"
jobs:
  build:
    name: "Autograding"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-dotnet@v1"
      with:
        dotnet-version: "6.0.x"
    - uses: "education/autograding@v1"

